In [1]:
import pandas as pd

file_path = '/content/drive/MyDrive/Upwork/patrick-bwn-project/TripAdvisor - State Based Search/tripadvisor_all_state_results.csv'
df = pd.read_csv(file_path)
display(df.head())

/tmp/ipykernel_2334/3970655515.py:4: DtypeWarning: Columns (5,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

,category,detail_id,title,ordinal,primary_info,secondary_info,tags,rating,review_count,badge_type,badge_year,description,latitude,longitude,url,photo_url,see_more_text,see_more_url
0,Attraction,1070936.0,Sight & Sound Theatres,1.0,Theaters,NaN,Theaters,4.9,8704.0,TRAVELLER_CHOICE,2026.0,Sight & Sound Theatres is the nation's largest...,36.665140,-93.26245,https://www.tripadvisor.com/Attraction_Review-...,https://dynamic-media-cdn.tripadvisor.com/medi...,NaN,NaN
1,Attraction,653837.0,The Haygoods,2.0,Theaters,NaN,Theaters,4.9,12433.0,TRAVELLER_CHOICE,2026.0,33rd SMASH-HIT SEASON! Celebrating 32 Years of...,36.637474,-93.27952,https://www.tripadvisor.com/Attraction_Review-...,https://dynamic-media-cdn.tripadvisor.com/medi...,See way to experience (1),https://www.tripadvisor.com/ClientLink?value=a...
2,Attraction,103201.0,Silver Dollar City,3.0,Amusement & Theme Parks • Water Parks,NaN,"Amusement & Theme Parks, Water Parks",4.4,12431.0,BEST_OF_BEST,2026.0,"Branson's #1 attraction for over 60 years, Sil...",36.668686,-93.33985,https://www.tripadvisor.com/Attraction_Review-...,https://dynamic-media-cdn.tripadvisor.com/medi...,NaN,NaN
3,Attraction,107810.0,City Museum,4.0,Speciality Museums,Downtown,Speciality Museums,4.7,6777.0,TRAVELLER_CHOICE,2026.0,Don't take the name so literally. We're about ...,38.633297,-90.20090,https://www.tripadvisor.com/Attraction_Review-...,https://dynamic-media-cdn.tripadvisor.com/medi...,See ways to experience (2),https://www.tripadvisor.com/ClientLink?value=d...
4,Attraction,104318.0,The Gateway Arch,5.0,Points of Interest & Landmarks • Observation D...,Downtown,"Points of Interest & Landmarks, Observation De...",4.4,12904.0,BEST_OF_BEST,2026.0,From the thrilling views to the amazing storie...,38.625126,-90.18675,https://www.tripadvisor.com/Attraction_Review-...,https://dynamic-media-cdn.tripadvisor.com/medi...,See ways to experience (12),https://www.tripadvisor.com/ClientLink?value=V...

In [2]:
print("Unique values per column:")
for column in df.columns:
    print(f"{column}: {df[column].nunique()} unique values")

Unique values per column:
category: 20 unique values
detail_id: 361565 unique values
title: 322524 unique values
ordinal: 9990 unique values
primary_info: 4033 unique values
secondary_info: 906 unique values
tags: 4033 unique values
rating: 41 unique values
review_count: 3430 unique values
badge_type: 2 unique values
badge_year: 1 unique values
description: 88197 unique values
latitude: 223955 unique values
longitude: 224038 unique values
url: 361566 unique values
photo_url: 200919 unique values
see_more_text: 140 unique values
see_more_url: 12946 unique values

In [3]:
unique_titles = df['title'].nunique()
print(f"Number of unique titles: {unique_titles}")

Number of unique titles: 322524

In [4]:
unique_primary_info = df['primary_info'].nunique()
print(f"Number of unique values in 'primary_info' column: {unique_primary_info}")

Number of unique values in 'primary_info' column: 4033

In [5]:
theaters_count = df[df['primary_info'] == 'Theaters'].shape[0]
print(f"Number of entries with 'primary_info' as 'Theaters': {theaters_count}")

print("\nFirst 5 entries where 'primary_info' is 'Theaters':")
display(df[df['primary_info'] == 'Theaters'].head())

Number of entries with 'primary_info' as 'Theaters': 3762

First 5 entries where 'primary_info' is 'Theaters':

,category,detail_id,title,ordinal,primary_info,secondary_info,tags,rating,review_count,badge_type,badge_year,description,latitude,longitude,url,photo_url,see_more_text,see_more_url
0,Attraction,1070936.0,Sight & Sound Theatres,1.0,Theaters,NaN,Theaters,4.9,8704.0,TRAVELLER_CHOICE,2026.0,Sight & Sound Theatres is the nation's largest...,36.665140,-93.26245,https://www.tripadvisor.com/Attraction_Review-...,https://dynamic-media-cdn.tripadvisor.com/medi...,NaN,NaN
1,Attraction,653837.0,The Haygoods,2.0,Theaters,NaN,Theaters,4.9,12433.0,TRAVELLER_CHOICE,2026.0,33rd SMASH-HIT SEASON! Celebrating 32 Years of...,36.637474,-93.27952,https://www.tripadvisor.com/Attraction_Review-...,https://dynamic-media-cdn.tripadvisor.com/medi...,See way to experience (1),https://www.tripadvisor.com/ClientLink?value=a...
17,Attraction,103196.0,Presleys' Country Jubilee,18.0,Theaters,NaN,Theaters,4.8,1989.0,TRAVELLER_CHOICE,2026.0,The first theater opened on Branson's famous H...,36.637856,-93.27476,https://www.tripadvisor.com/Attraction_Review-...,https://dynamic-media-cdn.tripadvisor.com/medi...,NaN,NaN
39,Attraction,1755660.0,Hughes Brothers Theatre,40.0,Theaters,NaN,Theaters,4.7,2060.0,TRAVELLER_CHOICE,2026.0,"Experience the Hughes Music Show, featuring th...",36.640350,-93.28430,https://www.tripadvisor.com/Attraction_Review-...,https://dynamic-media-cdn.tripadvisor.com/medi...,NaN,NaN
50,Attraction,948096.0,The Fabulous Fox Theatre,51.0,Theaters,Grand Center / Midtown,Theaters,4.7,891.0,NaN,NaN,The Fabulous Fox Theatre first opened in 1929 ...,38.638890,-90.23180,https://www.tripadvisor.com/Attraction_Review-...,https://dynamic-media-cdn.tripadvisor.com/medi...,NaN,NaN

In [10]:
print("Top 30 most frequent values in 'badge_type' column:")
display(df['badge_type'].value_counts().head(30))

Top 30 most frequent values in 'badge_type' column:

badge_type
TRAVELLER_CHOICE    2484
BEST_OF_BEST          62
Name: count, dtype: int64